language: node_js
node_js:
  - "9"
cache: yarn
deploy:
  - provider: npm
    skip_cleanup: true
    email: kevin@lewistech.com
    on:
      branch: master
    api_key:
      secure: MwfO90ZlIdoDRhI8qXgkrnKg6lfUlGKIbwlzZgwBEaVdU4dGxre6NKeZNSo5MFRaRekqAjn/vWZHI4Wk40hkzgyEnQW6tDrCSsVp7H7dl2Qq5Qon9AtAIfjnVgFdX9hZTGXX1uRxoJNFa4CTIUsbcFknbMDEVyuKr6+nFuNuWbvtAeW9/Rja2iw0TZ13fsmJPn5qHRc9cLfIa3FtU+b2euWcCuMcRWAx+ZFlBc0f3l5VojruDTjLUw8pZL8ZZ86DCR5DifDAyp8F+mTuRjoxTC7UPQfg/c5Nd5adxyRpKO0Utmcz3aSEd5tsJ6TSY5XHIjhfnHT86BLCUhdET9OBka2M60MqqgMfvwNwghqeqvHSXDw6aLKotK2xEvHyuRe2KizXrPZKKxfF6DPXlWxxTnc+k2gMdJ+rgr8vWaDm6iO79tjm6AHKI7uZkzTxwHe04yF6dcG0HzUO+2HGXp0cmBoqVX9ibN5pXdkxh7Eym/w+L1SiLZGjVDjuwvjZsPiZTB/7tAQeDLISYfK4vRubXwNXEvcxsYIYhA4Mc2eS0Zvbo628xQySE1i6tiKhhIlRnuoCHuhTwk3imi6s3zTmjisflShiB4jJhT5gib7IPJyuJyt1yZ13mkq+ExAWK8PEnubZATdNMT7ALJBBi2YJcRNTLizESx85g2DtI9mz6+4=
  - provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
    target_branch: gh-pages
    local_dir: gh-pages   
script:
  - gulp build examples coveralls gh-pages